# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QNRTCLiveDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QNRTCLiveDemo

  pod 'QNRTCKit', '3.0.0'
  pod 'Masonry', '1.0.2'
  pod 'PLPlayerKit','3.4.3'
  pod 'HappyDNS','0.3.17'
  pod 'RongCloudIM/IMKit','2.10.4'
  pod 'jetfire'
  pod 'MJRefresh'

  target 'QNRTCLiveDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
